#!/usr/bin/env python3
"""
Script to insert a document in the collection school in MongoDB.
"""

import pymongo
import sys


def insert_document(database_name):
    """Function to insert a document in the collection school in MongoDB."""

    client = pymongo.MongoClient('mongodb://localhost:27017/')

    db = client[database_name]

    collection = db['school']

    document = {"name": "Holberton school"}
    result = collection.insert_one(document)

    print(result)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <database_name>".format(sys.argv[0]))
        sys.exit(1)

    database_name = sys.argv[1]
    insert_document(database_name)
