#!/usr/bin/env python3
"""
Script to list all documents with name="Holberton school"
in the collection school in MongoDB.
"""

import pymongo
import sys


def match_documents(database_name):
    """Function to list all documents with name="Holberton school"
    in the collection school in MongoDB."""
    client = pymongo.MongoClient('mongodb://localhost:27017/')

    db = client[database_name]

    collection = db['school']

    documents = collection.find({"name": "Holberton school"})

    for doc in documents:
        print(doc)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <database_name>".format(sys.argv[0]))
        sys.exit(1)

    database_name = sys.argv[1]
    match_documents(database_name)
