#!/usr/bin/env python3
"""
Script to display the number of documents in the
collection school in MongoDB.
"""

import pymongo
import sys


def count_documents(database_name):
    """Function to display the number of documents in the
    collection school in MongoDB."""
    client = pymongo.MongoClient('mongodb://localhost:27017/')
    db = client[database_name]
    collection = db['school']
    count = collection.count_documents({})
    print(count)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <database_name>".format(sys.argv[0]))
        sys.exit(1)

    database_name = sys.argv[1]
    count_documents(database_name)
